{% set name = "experimentor" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/experimentor-{{ version }}.tar.gz
  sha256: 92e7ac6bdc5ca3bbf5ee962b1117efb84832126f3cb6b7dcc54d04bd49c0f196

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pint
    - numpy

test:
  imports:
    - experimentor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aquilesC/experimentor
  summary: Basic building blocks for controlling complex setups
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aquilesC
